### ISSUE TITLE
ssr:start crash 

### ISSUE THREAD

**Issue by germsb** [vueneue/vueneue#12]
On windows 10, create new project, add vueneue plugin, ``ssr:build`` -> ``ssr:start`` ->
```
(node:7340) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'c:\dev\testssr7\dist\index.spa.html'
    at Object.openSync (fs.js:443:3)
    at readFileSync (fs.js:348:35)
    at module.exports (c:\dev\testssr7\node_modules\@vueneue\ssr-server\lib\index.js:53:33)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:746:11)
    at startup (internal/bootstrap/node.js:240:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:564:3)
(node:7340) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7340) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
``ssr:serve`` work fine.

**Comment by chymz** [comment]
Sorry, I've fixed this, I will publish a new release today

**Comment by chymz** [comment]
Fix:

```bash
# Npm
npm update @vueneue/ssr-server@latest
# Yarn
yarn upgrade
```
