### ISSUE TITLE
npm run generate produces error: ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by sebastianhaeni** [vueneue/vueneue#23]
When running `npm run generate`, the following error occurs:

    ReferenceError: regeneratorRuntime is not defined
        at server-bundle.js:1:9883
        at Module.7cea (node_modules/@vueneue/ssr-core/utils/asyncData.js:44:14)
        at i (webpack/bootstrap:36:0)
        at Object.0 (webpack:/external "core-js/modules/es7.promise.finally":1:0)
        at i (webpack/bootstrap:36:0)
        at module.exports.0 (webpack/bootstrap:116:0)
        at Object.<anonymous> (webpack:/external "core-js/modules/es7.promise.finally":1:0)
        at evaluateModule (D:\repos\neue-examples\node_modules\vue-server-renderer\build.js:8349:21)
        at D:\repos\neue-examples\node_modules\vue-server-renderer\build.js:8407:18
        at new Promise (<anonymous>)
        at D:\repos\neue-examples\node_modules\vue-server-renderer\build.js:8399:14
        at Object.renderToString (D:\repos\neue-examples\node_modules\vue-server-renderer\build.js:8575:9)
        at Promise (D:\repos\neue-examples\node_modules\@vueneue\vue-cli-plugin-ssr\lib\generate.js:58:16)
        at new Promise (<anonymous>)
        at callRenderer (D:\repos\neue-examples\node_modules\@vueneue\vue-cli-plugin-ssr\lib\generate.js:57:12)
        at module.exports (D:\repos\neue-examples\node_modules\@vueneue\vue-cli-plugin-ssr\lib\generate.js:91:32)

To reproduce you can use https://github.com/vueneue/examples.

NodeJS version: 10.6.0

**Comment by chymz** [comment]
Temporary fix: install `regenarator-runtime` package
