### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by JimmyLv** [vueneue/vueneue#42]
It is broken when `vue add @vueneue/ssr`:

```
🚀  Invoking generator for @vueneue/vue-cli-plugin-ssr...
 ERROR  TypeError: Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at Context.visitNewExpression (/Users/Jing/c/casaba_sea/cs-front-end/node_modules/@vueneue/vue-cli-plugin-ssr/lib/recast.js:108:34)
    at Context.invokeVisitorMethod (/Users/Jing/c/casaba_sea/cs-front-end/node_modules/ast-types/lib/path-visitor.js:344:49)
    at Visitor.PVp.visitWithoutReset (/Users/Jing/c/casaba_sea/cs-front-end/node_modules/ast-types/lib/path-visitor.js:196:32)
    at visitChildren (/Users/Jing/c/casaba_sea/cs-front-end/node_modules/ast-types/lib/path-visitor.js:246:25)
    at Visitor.PVp.visitWithoutReset (/Users/Jing/c/casaba_sea/cs-front-end/node_modules/ast-types/lib/path-visitor.js:204:20)
    at NodePath.each (/Users/Jing/c/casaba_sea/cs-front-end/node_modules/ast-types/lib/path.js:101:26)
    at visitChildren (/Users/Jing/c/casaba_sea/cs-front-end/node_modules/ast-types/lib/path-visitor.js:219:18)
    at Visitor.PVp.visitWithoutReset (/Users/Jing/c/casaba_sea/cs-front-end/node_modules/ast-types/lib/path-visitor.js:204:20)
    at visitChildren (/Users/Jing/c/casaba_sea/cs-front-end/node_modules/ast-types/lib/path-visitor.js:246:25)
    at Visitor.PVp.visitWithoutReset (/Users/Jing/c/casaba_sea/cs-front-end/node_modules/ast-types/lib/path-visitor.js:204:20)
```

**Comment by chymz** [comment]
Can you share code from your Router, Store or i18n instanciation files ?

It seems plugin cannot convert `export default new ...` to an arrow function
