### ISSUE TITLE
VueSSR + Vuetify Alacarte

### ISSUE THREAD

**Issue by gmarke** [vueneue/vueneue#49]
Hi, 
there is a problem to have it working together as in subject.
When trying it throw error like that:

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (test/vue-test/node_modules/vuetify/es5/components/VApp/VApp.js:13:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)

I would be hppy to provide some more information if the one above is not necessary.

**Comment by chymz** [comment]
Can you share a github repository to reproduce your issue ?

**Comment by gmarke** [comment]
there you go: 
https://github.com/gmarke/alacarte

I think the problem is with config of webpack - not supporting stylus-loder but I don't know how to fix it

**Comment by chymz** [comment]
Thanks ! Weird issue, I've never used stylus.

I'll investigate on this next week

**Comment by chymz** [comment]
Style loader is already handled by Vue CLI webpack config, that's why it works in SPA mode.
It seems stylus loader dont do his job for server bundle.

**Comment by chymz** [comment]
There is a particular config for Vuetify Alacarte on Nuxt:

https://github.com/vuetifyjs/nuxt/blob/master/template/nuxt.config.js#L29-L41

**Comment by chymz** [comment]
Here is the solution:

In `vue.config.js`:

```js
module.exports = {
  transpileDependencies: [/^vuetify/],
  pwa: {
    workboxOptions: {
      templatedUrls: {
        '/': 'index.ssr.html',
      },
    },
  },
};
```

**Comment by gmarke** [comment]
Great!!

That's working - Thanks a lot.
So it was not webpack but most important is that is working..
