### ISSUE TITLE
Error: write EPIPE       at WriteWrap.afterWrite [as oncomplete] (net.js:835:14)

### ISSUE THREAD

**Issue by JimmyLv** [vueneue/vueneue#54]
```
node -v
v10.9.0
```

```bash
vue-cli-service ssr:build --mode production
vue-cli-service ssr:start
```

then we met the issue blow, cause we can't load js files from ssr:

```js

  Error: write EPIPE
      at WriteWrap.afterWrite [as oncomplete] (net.js:835:14)

```

**Comment by chymz** [comment]
Sorry I cant reproduce with https://github.com/vueneue/examples
